import { InitialStateTypes } from './types';

export const initialState: InitialStateTypes = {
  videosList: [
    {
      response_json: {
        artists: [],
        artists_sort: '',
        blocked_from_sale: false,
        community: {},
        companies: [],
        country: '',
        data_quality: '',
        date_added: '',
        date_changed: '',
        estimated_weight: undefined,
        extraartists: [],
        format_quantity: undefined,
        formats: [],
        genres: [],
        id: undefined,
        identifiers: [],
        images: [],
        labels: [],
        lowest_price: undefined,
        num_for_sale: undefined,
        released: '',
        released_formatted: '',
        resource_url: '',
        series: [],
        status: '',
        styles: [],
        thumb: '',
        title: '',
        tracklist: [],
        uri: '',
        videos: [{ uri: '' }],
        year: undefined,
      },
      img_url: '',
    },
  ],
  currentImage: undefined,
};
