export const LOAD_RECORDS_BY_USERNAME_SUCCESS = "LOAD_RECORDS_BY_USERNAME_SUCCESS";
export const LOAD_RECORDS_BY_USERNAME_ERROR = "LOAD_TRACKS_BY_USERNAME_ERROR";

export const LOAD_RECORD_BY_ID_SUCCESS = "LOAD_RECORD_BY_ID_SUCCESS";
export const LOAD_RECORD_BY_ID_ERROR = "LOAD_RECORD_BY_ID_ERROR";

export const GET_RECORD_DETAILS = "GET_RECORD_DETAILS";

export const FETCH_YOUTUBE_VIDEOS = "FETCH_YOUTUBE_VIDEOS";
export const RECEIVE_YOUTUBE_VIDEOS_SUCCESS = "RECEIVE_YOUTUBE_VIDEOS_SUCCESS";

export const HOVER_STATE_ACTIVE = "HOVER_STATE_ACTIVE";
export const HOVER_STATE_INACTIVE = "HOVER_STATE_INACTIVE";

export const LOADING_SPINNER_ACTIVE = "LOADING_SPINNER_ACTIVE";
export const LOADING_SPINNER_INACTIVE = "LOADING_SPINNER_INACTIVE";

export const TICK_YOUTUBE_PROGRESS_BAR = "TICK_YOUTUBE_PROGRESS_BAR";

export const SET_ALBUM_IMAGE = "SET_ALBUM_IMAGE";
