export const ADD_ITEM = 'ADD_ITEM'

export const LOAD_RECORDS_BY_USERNAME_SUCCESS = 'LOAD_RECORDS_BY_USERNAME_SUCCESS'
export const LOAD_RECORDS_BY_USERNAME_ERROR = 'LOAD_TRACKS_BY_USERNAME_ERROR'

export const LOAD_RECORD_BY_ID_SUCCESS = 'LOAD_RECORD_BY_ID_SUCCESS'
export const LOAD_RECORD_BY_ID_ERROR = 'LOAD_RECORD_BY_ID_ERROR'

export const GET_RECORD_DETAILS = 'GET_RECORD_DETAILS'
