export const ADD_ITEM = 'ADD_ITEM'

export const LOAD_RECORDS_SUCCESS = 'LOAD_RECORDS_SUCCESS'
export const LOAD_RECORDS_ERROR = 'LOAD_TRACKS_ERROR'

export const GET_RECORD_DETAILS = "GET_RECORD_DETAILS"